package model;

/**
 * Created by unity on 18.04.18.
 */
public enum Type {
    INT, BOOL, STRING, GAME, PLAYER,
    BOOL_INST,
    IF,ELSE,
    WHILE,
    END_OF_FILE,
    EMPTY,
    IDENTIFIER,

    EQUALLY,
    OPEN_BRACE, CLOSED_BRACE, OPEN_CURLY_BRACE, CLOSED_CURLY_BRACE,
    DOT, SEMICOLON, COMMA,

    RELATIONAL_OPERATOR,
    ARITHMETIC_OPERATOR,
    LOGICAL_OPERATOR,

    WAIT,

    GAME_ATTR, PLAYER_ATTR,
    GAME_FUN, PLAYER_FUN,

    //GRA
    START_GAME, END_GAME, FIND_WINNER,
    STATUS, BANK, WINER, PLAYER_COUNT,

    //PLAYER
    JOIN_GAME, LEAVE_GAME,
    BALANCE, STRING_INST, INT_INST, NAME
}
